apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: ApplicationMonitoring
metadata:
  name: example-applicationmonitoring
spec:
  labelSelector: "middleware"
  blackboxTargets:
    - service: nexus
      url: http://nexus.nexus:8081/nexus/content/groups/public
      module: http_2xx
