apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: ApplicationMonitoring
metadata:
  name: example-applicationmonitoring
spec:
  labelSelector: "middleware"
  blackboxTargets:
    - service: example
      url: https://example.com
      module: http_extern_2xx
