apiVersion: v1
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 12h
      receiver: default
      routes:
      - match:
          alertname: DeadMansSwitch
        repeat_interval: 5m
        receiver: deadmansswitch
    receivers:
    - name: default
    - name: deadmansswitch
    inhibit_rules:
    - source_match:
        alertname: 'JobRunningTimeExceeded'
        severity: 'critical'
      target_match:
        alertname: 'JobRunningTimeExceeded'
        severity: 'warning'
      equal: ['alertname', 'job', 'label_cronjob_name']
kind: Secret
metadata:
  name: alertmanager-application-monitoring
  namespace: {{ .Namespace }}
  type: Opaque
