apiVersion: v1
data:
  session_secret: >-
    {{.AlertManagerSessionSecret}}
kind: Secret
metadata:
  labels:
    k8s-app: alertmanager-k8s
  name: alertmanager-k8s-proxy
  namespace: {{.Namespace }}
type: Opaque