apiVersion: v1
kind: Service
metadata:
  name: {{ .AlertManagerServiceName }}
  namespace: {{ .Namespace }}
spec:
  ports:
    - name: web
      port: 6783
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: {{ .ApplicationMonitoringName }}
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP