apiVersion: v1
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: default
      routes:
      - match:
          alertname: DeadMansSwitch
        repeat_interval: 5m
        receiver: deadmansswitch
    receivers:
    - name: default
    - name: deadmansswitch
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname']
kind: Secret
metadata:
  name: alertmanager-application-monitoring
  namespace: {{ .Namespace }}
  type: Opaque
