apiVersion: v1
data:
  blackbox.yml: |-
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: ip4
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            cert_file: /etc/tls/private/tls.crt
            key_file: /etc/tls/private/tls.key
      http_post_2xx:
        prober: http
        http:
          method: POST
          preferred_ip_protocol: ip4
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            cert_file: /etc/tls/private/tls.crt
            key_file: /etc/tls/private/tls.key
kind: ConfigMap
metadata:
  name: {{ .BlackboxExporterConfigmapName }}
  namespace: {{ .Namespace }}
