apiVersion: v1
kind: Service
metadata:
  labels:
    application-monitoring: "true"
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-k8s-tls
  name: {{ .GrafanaServiceName }}
  namespace: {{ .Namespace }}
spec:
  ports:
    - name: grafana
      port: 9091
      protocol: TCP
      targetPort: grafana-proxy
    - name: asdf
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app: grafana