apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .GrafanaRouteName }}
  namespace: {{ .Namespace }}
spec:
  port:
    targetPort: grafana
  tls:
    termination: Reencrypt
  to:
    kind: Service
    name: {{ .GrafanaServiceName }}
  wildcardPolicy: None