apiVersion: v1
data:
  session_secret: >-
    {{.PrometheusSessionSecret}}
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-k8s
  name: prometheus-k8s-proxy
  namespace: {{.Namespace }}
type: Opaque