apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: 'middleware'
  name: {{ .PrometheusServiceMonitorName }}
  namespace: {{ .Namespace }}
spec:
  endpoints:
    - port: web
  selector:
    matchLabels:
      application-monitoring: 'true'