apiVersion: v1
kind: Service
metadata:
  name: alertmanager-application-monitoring
  namespace: {{ .Namespace }}
spec:
  ports:
    - name: web
      port: 6783
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: application-monitoring
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
