apiVersion: v1
kind: Service
metadata:
  name: {{ .PrometheusServiceName }}
  namespace: {{ .Namespace }}
  labels:
    application-monitoring: "true"
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app: prometheus