apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .ApplicationMonitoringName }}
  namespace: {{ .Namespace }}
  labels:
    prometheus: {{ .ApplicationMonitoringName }}
spec:
  externalUrl: https://{{ index .ExtraParams "prometheusHost" }}
  alerting:
    alertmanagers:
      - name: {{ .AlertManagerServiceName }}
        namespace: {{ .Namespace }}
        port: web
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus-application-monitoring
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring-key: 'middleware'
  serviceMonitorSelector:
    matchLabels:
      monitoring-key: 'middleware'
  ruleSelector:
    matchLabels:
      monitoring-key: 'middleware'
  ruleNamespaceSelector:
    matchLabels:
      monitoring-key: 'middleware'