apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: 'middleware'
  name: grafana
  namespace: {{ .Namespace }}
spec:
  endpoints:
    - port: grafana
      scheme: http
  selector:
    matchLabels:
      application-monitoring: 'true'