apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .PrometheusRouteName }}
  namespace: {{ .Namespace }}
spec:
  port:
    targetPort: web
  tls:
    termination: Reencrypt
  to:
    kind: Service
    name: {{ .PrometheusServiceName }}
  wildcardPolicy: None