apiVersion: v1
kind: Service
metadata:
  name: {{ .PrometheusServiceName }}
  namespace: {{ .Namespace }}
  labels:
    application-monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app: prometheus
  sessionAffinity: None