apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .ApplicationMonitoringName }}
  namespace: {{ .Namespace }}
  labels:
    prometheus: {{ .ApplicationMonitoringName }}
spec:
  baseImage: registry.redhat.io/openshift3/prometheus
  tag: v3.11
  containers:
    - args:
        - '-provider=openshift'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9090'
        - '-openshift-service-account=prometheus-application-monitoring'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb":"get"}}'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
      image: 'registry.redhat.io/openshift3/oauth-proxy:v3.11.43'
      name: prometheus-proxy
      ports:
        - containerPort: 9091
          name: oproxy
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-prometheus-k8s-tls
        - mountPath: /etc/proxy/secrets
          name: secret-prometheus-k8s-proxy
  externalUrl: https://{{ index .ExtraParams "prometheusHost" }}
  alerting:
    alertmanagers:
      - name: {{ .AlertManagerServiceName }}
        namespace: {{ .Namespace }}
        port: web
  resources:
    requests:
      memory: 400Mi
  secrets:
    - prometheus-k8s-tls
    - prometheus-k8s-proxy
  serviceAccountName: prometheus-application-monitoring
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring-key: {{ .MonitoringKey }}
  serviceMonitorSelector:
    matchLabels:
      monitoring-key: {{ .MonitoringKey }}
  ruleSelector:
    matchLabels:
      monitoring-key: {{ .MonitoringKey }}
  ruleNamespaceSelector:
    matchLabels:
      monitoring-key: {{ .MonitoringKey }}
